<?php $x = prov((int)($_GET['id'] ?? 1)); $busy = []; foreach ($x[11] as $r) for ($i = $r[0]; $i <= $r[1]; $i++) $busy[date('Y-m-d', strtotime("+$i days"))] = 1;
$ym = date('Y-m'); $lead = (int)date('N', strtotime("$ym-01")) - 1; ?>
<div class="row g-3"><div class="col-lg-8"><div class="card p-4"><div class="d-flex gap-3 align-items-center"><div class="avatar" style="width:72px;height:72px;font-size:28px"><?= e($x[1][0]) ?></div>
<div><h2 class="mb-1"><?= e($x[1]) ?></h2><?= vbadge($x[6]) ?> <span class="badge text-bg-light border"><?= ucfirst($x[2]) ?></span></div></div>
<p class="mt-3"><?= e($x[9]) ?></p><ul class="list-unstyled small"><li><i class="bi bi-geo-alt"></i> <?= e($x[3]) ?> County</li><li><i class="bi bi-translate"></i> <?= e($x[4]) ?></li><li><i class="bi bi-cash"></i> $<?= $x[5] ?> per day</li>
<?php if ($x[10]) echo '<li><i class="bi bi-truck-front"></i> ' . e($x[10]) . '</li>'; ?><li><?= stars($x[7]) ?> (<?= $x[8] ?> reviews)</li></ul>
<h5>Verification</h5><ul class="small"><li><?= $x[6] ? '✅' : '⏳' ?> Identity document</li><li><?= $x[6] ? '✅' : '⏳' ?> <?= $x[2] == 'guide' ? 'Tourism guide licence' : 'PSV / driving licence' ?></li><li><?= $x[6] ? '✅' : '⏳' ?> Admin review</li></ul></div>
<div class="card p-4 mt-3" id="availability"><h5>Availability — <?= date('F Y') ?></h5><div class="cal"><?php foreach (['M','T','W','T','F','S','S'] as $h) echo "<div class='h'>$h</div>"; for ($i = 0; $i < $lead; $i++) echo "<div class='e'></div>";
for ($d = 1; $d <= (int)date('t'); $d++) { $k = date('Y-m-') . sprintf('%02d', $d); echo '<div class="' . (isset($busy[$k]) ? 'x' : '') . '">' . $d . '</div>'; } ?></div><small class="text-body-secondary">Green = available · struck-through = booked</small></div></div>
<div class="col-lg-4"><form data-demo class="card p-4"><h5>Request a booking</h5><label class="form-label small">From</label><input type="date" class="form-control mb-2" required><label class="form-label small">To</label><input type="date" class="form-control mb-2" required>
<label class="form-label small">Travelers</label><input type="number" min="1" value="2" class="form-control mb-2"><label class="form-label small">Notes</label><textarea class="form-control mb-3" rows="3" placeholder="Where would you like to go?"></textarea><button class="btn btn-accent w-100">Send request</button></form>
<div class="card p-3 mt-3"><h6>Reviews</h6><div class="small"><?= stars(5) ?> “Unforgettable trip, very knowledgeable.” — Sarah M.</div><div class="small mt-2"><?= stars(4.5) ?> “Punctual and friendly.” — Daniel K.</div></div></div></div>
